apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLResolverMap
metadata:
  name: bookinfo-rest-resolvermap
  namespace: bookinfo
spec:
  types:
    # Top-level query type
    Query:
      fields:
        productsForHome:
          resolvers:
          - restResolver:
              destinations:
              - port:
                  number: 9080
                ref:
                  name: productpage
                  namespace: bookinfo
                  cluster: mgmt
              request:
                headers:
                  :path:
                    jq: '"/api/v1/products"'
    # Product object type
    Product:
      fields:
        ratings:
          resolvers:
          - resolverResultTransform:
              jq: '.resolverResultVar.ratings | to_entries | map(.reviewer=.key | .numStars=.value | del(.key,.value))'
            restResolver:
              destinations:
              - port:
                  number: 9080
                ref:
                  name: ratings
                  namespace: bookinfo
                  cluster: mgmt
              request:
                headers:
                  :path:
                    jq: '"/ratings/" + (.parentVar.id | tostring)'
          variables:
            parentVar:
              graphqlParent: {}
            resolverResultVar:
              resolverResult: {}
        reviews:
          resolvers:
          - resolverResultTransform:
              jq: '.resolverResultVar.reviews'
            restResolver:
              destinations:
              - port:
                  number: 9080
                ref:
                  name: reviews
                  namespace: bookinfo
                  cluster: mgmt 
              request:
                headers:
                  :path:
                    jq: '"/reviews/" + (.parentVar.id | tostring)'
          variables:
            parentVar:
              graphqlParent: {}
            resolverResultVar:
              resolverResult: {}