apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLSchema
metadata:
  name: bookinfo-rest-graphqlschema
  namespace: bookinfo
spec:
  resolved:
    options: {}
    resolverMapRefs:
    - name: bookinfo-rest-resolvermap
      namespace: bookinfo
      clusterName: mgmt
  schemaRef:
    name: bookinfo-rest-apidoc
    namespace: bookinfo
    clusterName: mgmt