apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: graphql-bookinfo
  namespace: bookinfo
spec:
  hosts:
  - httpbin.example.com
  http:
  - name: graphql-bookinfo
    labels:
      route: graphql-bookinfo
    graphql:
      schema:
        name: bookinfo-rest-graphqlschema
        namespace: bookinfo
        clusterName: mgmt
    matchers:
    - uri:
        prefix: /graphql
  virtualGateways:
  - name: istio-ingressgateway
    namespace: bookinfo