---
apiVersion: security.policy.gloo.solo.io/v2
kind: CORSPolicy
metadata:
  name: graphql-explorer
  namespace: bookinfo
spec:
  applyToRoutes:
  - route:
      labels:
        route: graphql-bookinfo
  config:
    allowCredentials: true
    allowHeaders:
    - content-type
    allowMethods:
    - POST
    allowOrigins:
    - regex: ".*"