apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-sample-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ky-rafaels/gloo-mesh-notes
    path: solo/app-configs/workload-cluster
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    # server: https://kubernetes.default.svc
    server: cluster1
    namespace: httpbin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s