# Here is an example to configure cross cluster ext-auth via 
# virtual destination on a target cluster
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  annotations:
    cluster.solo.io/cluster: ""
  name: ext-auth-service-global
  namespace: gloo-mesh-addons
spec:
  hosts:
  - ext-auth-service.vd
  ports:
  - number: 8083
    protocol: GRPC
  services:
  - labels:
      app: ext-auth-service
---
apiVersion: admin.gloo.solo.io/v2
kind: ExtAuthServer
metadata:
  annotations:
    cluster.solo.io/cluster: ""
  name: default-server
  namespace: bookinfo
spec:
  destinationServer:
    kind: VIRTUAL_DESTINATION
    ref:
      cluster: mgmt
      name: ext-auth-service-global
      namespace: gloo-mesh-addons