---
apiVersion: security.policy.gloo.solo.io/v2
kind: JWTPolicy
metadata:
  annotations:
    cluster.solo.io/cluster: ""
  name: jwt-policy
  namespace: bookinfo
spec:
  applyToDestinations:
    - selector:
        labels:
          app: details
    - selector:
        labels:
          app: ratings
    - selector:
        labels:
          app: reviews
  config:
    phase:
      preAuthz: {}
    providers:
      dev-example:
        keepToken: true
        claimsToHeaders:
          - append: true
            claim: org
            header: x-org
          - append: true
            claim: email
            header: x-email
        issuer: https://dev.example.com
        remote:
          url: <url>/keys
        tokenSource:
          headers:
            - name: jwt