---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-eastwest
  namespace: argocd
spec:
  generators:
    - clusters: {} 
  template:
    metadata:
      name: "istio-eastwest"
    spec:
      project: default
      source: 
        repoURL: 'https://github.com/ky-rafaels/gloo-mesh-notes.git' 
        targetRevision: main 
        path: istio/1.20-solo/istio-eastwest
        helm:
          releaseName: istio-eastwest
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            # - values-{{ env }}.yaml
      destination:
        name: "in-cluster"
        namespace: 'istio-eastwest'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true