---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-lifecycle-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ky-rafaels/gloo-mesh-notes
    path: solo/single-cluster/lifecycle-managers
    targetRevision: HEAD
  destination:
    # server: https://kubernetes.default.svc
    server: mgmt
    namespace: gloo-mesh 
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s