---
apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: north-south-gateway
  namespace: gloo-mesh
spec:
  installations:
    - clusters:
      - name: mgmt
        activeGateway: true
      gatewayRevision: 1-20-test
      istioOperatorSpec:
        profile: empty
        hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
        tag: 1.20.2-solo
        # values:
        #   gateways:
        #     istio-ingressgateway:
        #       customService: true
        components:
          ingressGateways:
            - name: istio-ingressgateway
              namespace: istio-gateways
              enabled: true
              label:
                istio: ingressgateway
