---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # annotations: 
    # argocd.argoproj.io/sync-wave: "-2"      # potentially configure a sync wave here
  name: gloo-platform-mgmt
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://storage.googleapis.com/gloo-platform/helm-charts
      targetRevision: 2.5.8
      helm:
        valueFiles:
        - $values/solo/single-cluster/gloo-values/mgmt-values.yaml
      chart: gloo-platform
    - repoURL: https://github.com/ky-rafaels/gloo-mesh-notes.git
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gloo-mesh
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true